name: Project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initialize checkout
      uses: actions/checkout@v2

    - name: Back-end - Build Docker Compose
      run: docker-compose build

    - name: Front-end - Initialize Java with SDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Front-end - Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./client

    - name: Front-end - Build Gradle
      run: ./gradlew build
      working-directory: ./client
